### PR TITLE
Add support for ARM systems

### PR DESCRIPTION
**Pull request by gohai**
Currently untested.

### CODE REVIEW

**Comment by gohai** [comment]
@shiffman @ThomasLengeling 
I believe I got the native library side figured out, but the example sketches throw a NullPointerException in the Kinect constructor for me. Let me know if you have an idea, else I'll debug this some more some other day.

I'll put a zip of the status quo up at http://sukzessiv.net/~gohai/p5-arm

Best
Gottfried

**Comment by ThomasLengeling** [comment]
Great it works, thank you!

**Comment by gohai** [comment]
@ThomasLengeling Does it work? (I got this NullPointerException.)

**Comment by ThomasLengeling** [comment]
Just don't compile the lib with the test file sources (org.openkinect.test), I'll fix this though

**Comment by gohai** [comment]
@ThomasLengeling That's not the problem, the problem I have is in the Kinect constructor. In Freenect.java, method createContext `ctxPtr.getValue()` is `NULL`, which makes NativeContext crash.

**Comment by gohai** [comment]
@ThomasLengeling The odd thing is that the return value of `freenect_init` is zero, indicating success, which shouldn't happen when the pointer of the stucture is `NULL`. Thinking perhaps something with JNA is amiss..

**Comment by gohai** [comment]
@ThomasLengeling (Fixed it here)

**Pull request merged**
